name: ci

on:
  push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:latest
      -
        name: Logout from Docker Hub
        run: docker logout
      -
        name: Send Email
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: smtp.freesmtpservers.com
          smtp-port: 25
          smtp-secure: false
          from-email: sender@example.com
          to-email: s118519@ap.be
          subject: Test Email
          body: This is a test email sent from GitHub Actions.
          html: |
            <h1>This is a test email</h1>
            <p>Test Paragraph</p>
